name: Release

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: 'I understand that this action will publish everything on canary to the latest tag'
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Merge canary into main
        uses: devmasx/merge-branch@8b86512c768bec19827894f0a39a776809668189
        with:
          type: now
          from_branch: canary
          target_branch: main
          github_token: ${{ secrets.RELEASE_BOT_PAT }}

      - name: Back-merge main into canary
        uses: devmasx/merge-branch@8b86512c768bec19827894f0a39a776809668189
        with:
          type: now
          from_branch: main
          target_branch: canary
          github_token: ${{ secrets.RELEASE_BOT_PAT }}
